version: '3.4'

services:
  backend:
    restart: on-failure
    build:
      context: ./materials-evaluation-dotnet/
    ports:
      - "5000:80"
    volumes:
      - ./materials-evaluation-dotnet:/App
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:80
    depends_on:
      - database

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: database
    restart: unless-stopped
    ports:
      - 1433:1433
    volumes:
      - ./../materials-evaluation-database/data:/var/opt/mssql/data
      - ./../materials-evaluation-database/log:/var/opt/mssql/log
      - ./../materials-evaluation-database/secrets:/var/opt/mssql/secrets
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "MaterialsEvaluation@123456789"

  # FIXME: o angular não funciona para hot-reload nessas configurações
  spa:
    restart: on-failure
    container_name: angular-ui
    build:
      context: ./materials-evaluation-spa/
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - 4200:4200
    volumes:
      - ./materials-evaluation-spa:/usr/src/app
      - /usr/src/app/web/node_modules
